/**
 * Harmony basic views.
 * Those view or view-related classes are generated by harmony to
 * manage the base generated project. Feel free to modify them.
 */
package com.maximeleau.harmony.android.pokemon.harmony.view;

